name: Latest blog post workflow
on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-readme-blog
  cancel-in-progress: false

jobs:
  update-readme-with-blog:
    name: Update README with Latest Blog Posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Update README with Blog Posts
        uses: gautamkrishnar/blog-post-workflow@v1.9.6
        with:
          feed_list: "https://blog.builtwithcaffeine.cloud/rss.xml"
          disable_item_validation: true
          item_exec: "if (!post.title) post = null;"
          date_format: yy-mm-dd
          readme_path: "./README.md"
          committer_username: "bwc-content-update"
          committer_email: "bwc-content-update@users.noreply.github.com"
