name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme


jobs:
  update-readme-with-blog:
    name: Update README with Latest Blog Posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Update README with Blog Posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://blog.builtwithcaffeine.cloud/rss.xml"
          item_exec: "if (!post.title) post = null;" #to skip post that dont have title
          readme_path: "./readme.md" # Ensure case matches your file system
