name: Latest blog post workflow
on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-readme-blog
  cancel-in-progress: false

jobs:
  update-readme-with-blog:
    name: Update README with Latest Blog Posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Update README with Blog Posts
        uses: gautamkrishnar/blog-post-workflow@f177491c77670f150ab4e9b9890254d8eba4164b # v1.9.7
        with:
          feed_list: "https://blog.builtwithcaffeine.cloud/rss.xml"
          disable_item_validation: true
          item_exec: "if (!post.title) post = null;"
          date_format: yy-mm-dd
          readme_path: "./readme.md"
          committer_username: "[BWC] Blog Content Updater"
          committer_email: "bwc-content-update@users.noreply.github.com"
